version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
 
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: codeany
      MONGO_INITDB_ROOT_PASSWORD: pass1234
    network_mode: service:app